name: Auto Tag Platforms on Version Change

on:
  push:
    branches:
      - main
    paths:
      - 'KartOs/KartOs_STM32/**'
      - 'KartOs/KartOs_ESP32/**'

jobs:
  #STM32 TAGGING
  tag-stm32:
    runs-on: ubuntu-latest
    permissons:
      contents: write
    outputs:
      changed: ${{ steps.check_changes.outputs.stm32 }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Double check if we're in the STM32 directory
      - name: Check for STM32 Changes
        id: check_changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            stm32:
              - 'KartOs/KartOs_STM32/**'

      - name: Process STM32 Version
        if: steps.check_changes.outputs.stm32 == 'true'
        run: |
          HEADER="KartOs/KartOs_STM32/Core/App/configuration.h"
          
          MAJOR=$(awk '/#define VERSION_MAJOR/ {print $3}' $HEADER)
          MINOR=$(awk '/#define VERSION_MINOR/ {print $3}' $HEADER)
          PATCH=$(awk '/#define VERSION_PATCH/ {print $3}' $HEADER)
          TAG_NAME="stm-$MAJOR.$MINOR.$PATCH"
          
          echo "Detected STM32 version: $TAG_NAME"
          
          if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
            echo "Tag $TAG_NAME already exists. Skipping."
          else
            echo "New STM32 version detected! Creating tag..."
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@://github.com"
            git tag "$TAG_NAME"
            git push origin "$TAG_NAME"
          fi

  #ESP32 TAGGING
  tag-esp32:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Double check if we're in ESP32 directory
      - name: Check for ESP32 Changes
        id: check_changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            esp32:
              - 'KartOs/KartOs_ESP32/**'

      - name: Process ESP32 Version
        if: steps.check_changes.outputs.esp32 == 'true'
        run: |
          HEADER="KartOs/KartOs_ESP32/main/configuration.h"
          
          MAJOR=$(awk '/#define VERSION_MAJOR/ {print $3}' $HEADER)
          MINOR=$(awk '/#define VERSION_MINOR/ {print $3}' $HEADER)
          PATCH=$(awk '/#define VERSION_PATCH/ {print $3}' $HEADER)
          TAG_NAME="esp-$MAJOR.$MINOR.$PATCH"
          
          echo "Detected ESP32 version: $TAG_NAME"
          
          if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
            echo "Tag $TAG_NAME already exists. Skipping."
          else
            echo "New ESP32 version detected! Creating tag..."
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@://github.com"
            git tag "$TAG_NAME"
            git push origin "$TAG_NAME"
          fi
